#!/bin/bash

export DESKTOP_CORE_NAME="postman"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=latest
export DESKTOP_CORE_MD5SUM=5eeac1c71caff672e99d3f4180f09233
export DESKTOP_CORE_ORG="postman"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/postman/releases/download"
