#!/bin/bash

install() {
  # prepare vars
  local name="$DESKTOP_CORE_NAME"

  log::info "[$(timestamp)][desktop][$name] preparing ..."

  # get system os/arch
  local os="$DESKTOP_OS"
  local arch="$DESKTOP_OS_ARCH"
  local kernel="$DESKTOP_OS_KERNEL"
  local platform="$DESKTOP_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$DESKTOP_USER_BIN_DIR"
  local cache_dir="$DESKTOP_CACHE_DIR"
  local tmp_dir="$DESKTOP_TMP_DIR"

  #
  case $platform in
  darwin) ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  # case $arch in
  # arm64) ;;

  # amd64)
  #   arch="x86_64"
  #   ;;
  # *)
  #   log::error "[$(timestamp)] unsupport arch: $arch"
  #   return 1
  #   ;;
  # esac
  # #

  # files
  local cache_file="$cache_dir/$DESKTOP_CORE_VERSION.zip"
  # local source_bin_file="./$name"

  # prepare context
  log::info "[$(timestamp)][desktop][$name] context: $tmp_dir ..."
  cd $tmp_dir
  
  local is_cached="false"
  if [ -f "$cache_file" ]; then
    local cache_file_checksum=$(os::sha256 $cache_file)
    local cache_file_checksum_expect=""

    case $DESKTOP_CORE_VERSION in
    v1.2.0)
      case $arch in
      arm64)
        cache_file_checksum_expect="f21853977b755dc8e0dfdcd218b3780808812673da92f669458e784a5cb752ee"
        ;;
      amd64)
        cache_file_checksum_expect="f21853977b755dc8e0dfdcd218b3780808812673da92f669458e784a5cb752ee"
        ;;
      esac
      ;;
    esac

    if [ "$cache_file_checksum" = "$cache_file_checksum_expect" ]; then
      is_cached="true"
    fi
  fi


  if [ "$is_cached" = "true" ]; then
    log::info "[$(timestamp)][desktop][$name] found cache at $cache_file ..."
  else
    # reference: https://github.com/9seconds/iterm2/releases
    # example:
    #   https://dl.pstmn.io/download/latest/osx_64
    #   https://dl.pstmn.io/download/latest/osx_arm64
    # generate url
    local url=""
    case $arch in
    arm64)
      url="https://dl.pstmn.io/download/latest/osx_64"
      ;;
    amd64)
      url="https://dl.pstmn.io/download/latest/osx_arm64"
      ;;
    *)
      log::error "[$(timestamp)] unsupport arch: $arch"
      return 1
      ;;
    esac

    log::debug "[$(timestamp)][desktop][$name][$kernel][$arch] url: $url, file: ${cache_file}, tmp_dir: $tmp_dir"

    # download
    log::info "[$(timestamp)][desktop][$name] downloading from $url ..."
    os::download $cache_file $url
  fi

  # install
  log::info "[$(timestamp)][desktop][$name] installing $cache_file ..."
  case $arch in
  arm64)
    install::zip $cache_file ${name} Postman.app 
    ;;
  amd64)
    install::zip $cache_file ${name} Postman.app 
    ;;
  *)
    log::error "[$(timestamp)] unsupport arch: $arch"
    return 1
    ;;
  esac

  # clean
  log::info "[$(timestamp)][desktop][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
